<a href="https://colab.research.google.com/github/JulianeVillena/LinearAlgebra_Villena1/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 4 Activity


In [1]:

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

**TASK 1**
Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix.
Displays whether the matrix is square or non-square.
Displays whether the matrix is an empty matrix.
Displays if the matrix is an identity, ones, or zeros matrix
Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [2]:
def mat_desc(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

SQUARE MATRIX

In [3]:

A = np.array([
    [1, 2, 4],
    [3, 1, 2],
    [3, 0, 5]
])
print(f'Square Matrix: \n{A}')
mat_desc(A)

Square Matrix: 
[[1 2 4]
 [3 1 2]
 [3 0 5]]
Matrix:
[[1 2 4]
 [3 1 2]
 [3 0 5]]

Shape:	(3, 3)
Rank:	2



ZERO MATRIX

In [4]:
zero_mat = np.zeros((3,3))
print(f'Zero Matrix: \n{zero_mat}')
mat_desc(zero_mat)

Zero Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(3, 3)
Rank:	2



ONES MATRIX

In [5]:
ones_mat = np.ones((5,5))
print(f'Ones Matrix: \n{ones_mat}')
mat_desc(ones_mat)

Ones Matrix: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Shape:	(5, 5)
Rank:	2



DIAGONAL MATRIX

In [6]:
B= np.array([
    [2,0,0,0,0],
    [0,4,0,0,0],
    [0,0,6,0,0],
    [0,6,0,5,0],
    [0,6,0,0,1],
])
print(f'Diagonal Matrix: \n{B}')
mat_desc(B)


Diagonal Matrix: 
[[2 0 0 0 0]
 [0 4 0 0 0]
 [0 0 6 0 0]
 [0 6 0 5 0]
 [0 6 0 0 1]]
Matrix:
[[2 0 0 0 0]
 [0 4 0 0 0]
 [0 0 6 0 0]
 [0 6 0 5 0]
 [0 6 0 0 1]]

Shape:	(5, 5)
Rank:	2



IDENTITY MATRIX

In [7]:

mat_identity = np.identity(7)
print(f'Identity Matrix: \n{mat_identity}')
mat_desc(mat_identity)

Identity Matrix: 
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
Matrix:
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]

Shape:	(7, 7)
Rank:	2



**TASK 2** Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.
Returns the sum of the matrices.
Returns the differen of the matrices.
Returns the element-wise multiplication of the matrices.
Returns the element-wise division of the matrices.
Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.


In [24]:
def mat_operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

ADDITION

In [23]:
A = np.array([
    [2,2,7],
    [2,6,3],
    [5,1,4]
])
B = np.array([
    [2,4,6],
    [4,3,6],
    [1,5,7]
])
A+B
print(f'Addition Matrix: \n{A+B}')

Addition Matrix: 
[[ 4  6 13]
 [ 6  9  9]
 [ 6  6 11]]


In [14]:
B = np.array([
    [2,5,0],
    [1,7,3],
    [5,2,4]
])
C = np.array([
    [2,0,6],
    [6,3,0],
    [2,0,5]
])

B+C
print(f'Addition Matrix: \n{B+C}')


Addition Matrix: 
[[ 4  5  6]
 [ 7 10  3]
 [ 7  2  9]]


SUBTRACTION

In [15]:
A = np.array([
    [2,2,7],
    [2,6,3],
    [5,1,4]
])
B = np.array([
    [2,4,6],
    [4,3,3],
    [1,5,5]
])

A-B
print(f'Subtraction Matrix: \n{A+B}')

Subtraction Matrix: 
[[ 4  6 13]
 [ 6  9  6]
 [ 6  6  9]]


ELEMENT-WISE MULTIPLICATION

In [26]:
A*B
print(f'Multiplication Matrix: \n{A*B}')

Multiplication Matrix: 
[[ 4  8 42]
 [ 8 18 18]
 [ 5  5 28]]


In [28]:
C*B
print(f'Multiplication Matrix: \n{C*B}')

Multiplication Matrix: 
[[ 4  0 36]
 [24  9  0]
 [ 2  0 35]]


ELEMENT-WISE DIVISION

In [30]:
A/B
print(f'Division Matrix: \n{A/B}')

Division Matrix: 
[[1.         0.5        1.16666667]
 [0.5        2.         0.5       ]
 [5.         0.2        0.57142857]]


In [33]:
B/A
print(f'Division Matrix: \n{B/A}')

Division Matrix: 
[[1.         2.         0.85714286]
 [2.         0.5        2.        ]
 [0.2        5.         1.75      ]]
