<a href="https://colab.research.google.com/github/JulianeVillena/LinearAlgebra_Villena1/blob/main/PRELIM_villena_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PRELIM EXAM (VILLENA)
Code solution

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [3]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [4]:
i = 0
while i < 5:
  print(i)
  i+= 1
  if i == 3:
      break
else:
  print(0)      

0
1
2


In [5]:
x = 1
while True:
   if x % 5 == 0:
       break
   print(x)
   x + = 1

SyntaxError: ignored

In [6]:
x, y, z = 2, 4.0, '3'
type(z)

str

In [7]:
d = {0,1,2}
for x in d:
  print(x)

0
1
2


In [8]:
P = np.array([
    [5,7,2],
    [2,3,3],
    [4,1,0]          
])
Q = np.array([
    [2,2,-3],
    [0,0,1],
    [1,1,-3]
]) 
P + 2*Q

array([[ 9, 11, -4],
       [ 2,  3,  5],
       [ 6,  3, -6]])

In [9]:
import numpy as np
X = np.array([
    [5,0,4],
    [4,-1,5],
    [3,-1,-6]
]) 

In [10]:
import numpy as np
A = np.array([[8,2],
    [5,4],
    [1,1]])
describe_mat(A)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [11]:
def create_user (userid):
    print("Successfully created user: {}".format(userid))

userid = 2021_100001
create_user(2021-100100)

Successfully created user: -98079


In [12]:
import numpy as np
a = np.array([[1,2,3],[0,1,4]])
print (a.shape)

(2, 3)


$$
B = \left\{
    \begin{array}\
      x+y+z\\
      3x-2y-z\\
      -x+4y+2z
    \end{array}
  \right.$$

In [13]:
import numpy as np
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c

array([1, 5, 7, 7, 9])

In [14]:
int1 = 10
int2 = 6
if int1 != int2:
    int2 = ++ int2
    print(int1 - int2)

4
